# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "deps.ipynb",
         "add_dvcr_commands": "deps.ipynb",
         "make_parser": "deps.ipynb",
         "DVC_RECORD_STRING": "deps.ipynb",
         "DVC_DRY_RUN": "deps.ipynb",
         "DO_NOT_INCLUDE_IN_PIPELINE": "deps.ipynb",
         "NoArgumentNamed": "deps.ipynb",
         "Dependency": "deps.ipynb",
         "Output": "output.ipynb",
         "ParamFile": "params.ipynb",
         "Params": "params.ipynb",
         "PipelineStage": "stage.ipynb",
         "maybe_yaml": "utils.ipynb",
         "write_yaml": "utils.ipynb",
         "PARAMS_FILE_DEFAULT": "utils.ipynb",
         "PIPELINE_FILE_DEFAULT": "utils.ipynb"}

modules = ["deps.py",
           "__init__.py",
           "output.py",
           "params.py",
           "stage.py",
           "utils.py"]

doc_url = "https://talosiot-will.github.io/dvcrecord/"

git_url = "https://github.com/talosiot-will/dvcrecord/tree/master/"

def custom_doc_links(name): return None
