# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/output.ipynb (unless otherwise specified).

__all__ = ['Output']

# Cell
import collections
from .utils import maybe_yaml
from .trackedfile import TrackedFile

class Output:
    def __init__(self):
        self.out_files = collections.OrderedDict({})

    def load(self, fpath, *args, **kwargs):
        '''
        Returns a file or directory name and records it
        '''
        tracked_file = self.out_files.setdefault(fpath, TrackedFile(fpath, *args, **kwargs))
        return tracked_file

    def render(self, as_yaml=False):
        returnme = [out_file.render(as_yaml=False) for out_file in self.out_files.values()]
        return maybe_yaml(returnme, as_yaml=as_yaml)
