# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/output.ipynb (unless otherwise specified).

__all__ = ['Output']

# Cell
import os
import collections
from .utils import maybe_yaml

class Output:
    def __init__(self):
        self.out_files = []

    def register(self, *args):
        fpath = os.path.join(*args)
        if fpath not in self.out_files:
            self.out_files.append(fpath)
        return fpath

    def render(self, as_yaml=False):
        return maybe_yaml(self.out_files, as_yaml=as_yaml)
