# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/utils.ipynb (unless otherwise specified).

__all__ = ['maybe_yaml', 'write_yaml', 'PARAMS_FILE_DEFAULT', 'PIPELINE_FILE_DEFAULT']

# Cell
import os
import yaml

PARAMS_FILE_DEFAULT = os.environ.get('DVC_PARAMETERS_FILE', 'params.yaml')
PIPELINE_FILE_DEFAULT = os.environ.get('DVC_PIPELINE_FILE', 'dvc.yaml')


def maybe_yaml(data, as_yaml=False):
    if as_yaml:
        return yaml.dump(data)
    return data

def write_yaml(params, folder='', fname='params.yaml'):
    fpath = os.path.join(folder, fname)
    with open(fpath, 'w') as f:
        yaml.dump(params, f)
    return fpath